### ISSUE TITLE
Missing NULL value after the signature algorithm field

### ISSUE THREAD

**Issue by williampiras** [wbond/csrbuilder#1]
Will,

the CSR generated by the library do not specify the NULL attribute for the parameter attribute of the signature algorithm element.

RFC 4055 (https://tools.ietf.org/html/rfc4055#section-2.1) is really confusing on this point, but the last paragraph of the section link above clarifies that in case of SHA\* algorithm the NULL value should be specified. I also verified that CSR created with OpenSSL set the field as NULL.  

The patch for this issue is as easy as specifying "null()" for the attribute and importing the core module that defines null(). If you want I can submit a pull request with the fix.

Thanks,
Will

**Comment by wbond** [comment]
The documentation referenced seems to be for PSS and OAEP.

Generally I try to follow the latest RFCs for the ASN.1 definitions, with workarounds for dealing with parsing broken encodings that some popular tools generate. Appendix A of RFC 2986 marks the parameters as optional: https://tools.ietf.org/html/rfc2986#appendix-A.

Unless you are having trouble parsing the output, I think it is currently correct.

**Comment by williampiras** [comment]
I definitely don't have a strong opinion about this. It is a minor issue that was flagged as a warning by a CA that I'm currently using, so I decided ot reported just in case other people noticed the same. I found this debugging a bigger issue with the ASN1 crypto package, but I'll open a separate issue to track that.

Back to the problem, the RFC that I mentioned is newer than the one you referred, but as I mentioned above is really confusing since it contradicts itself in more than one part. The RFC specifies how to represents the set of new additional algorithms and identifiers for  X.509 PKI certificates and CRL (interested that they left out the CSRs part, but considering the application it must extend to that too). My take on the doc is that the representation for a generic algorithm identifier must not be specified, but when specified it has to be NULL. With that said, for certain algorithm the standard explicitly states that the parameter must be NULL, and for other it states a different value. This is confirmed by the ASN.1 module part of the document (https://tools.ietf.org/html/rfc4055#page-16) where we see that some of the algorithm specify nullParameters parametes

```
    _sha256Identifier    AlgorithmIdentifier  ::=  {
                          algorithm id-sha256,
                          parameters nullParameters  }_
```

and some of them specify values

```
_rSASSA-PSS-Default-Identifier  AlgorithmIdentifier  ::=  {
                          algorithm id-RSASSA-PSS,
                          parameters rSASSA-PSS-Default-Params }_
```

Also notice that CSRs generated by OpenSSL (I assume it's fair considering the library the industry standard/reference implementation when it comes to this kind of problems) have a parameter value set according to this RFC. Here's the longer OpenSSL thread on the topic:

https://mta.openssl.org/pipermail/openssl-dev/2015-January/000441.html

From the tests that I run I see that the library generates CSRs that contain the NULL parameter, but it also correctly verifies CSRs that do not specify it (therefore CSRs generated with the last version available of the lib).

**Comment by wbond** [comment]
Ok, so on [page 15](https://tools.ietf.org/html/rfc4055#page-15) it does make it clear that `Null` should be included when those specific OIDs are used, and [CertificationRequest](https://github.com/wbond/asn1crypto/blob/master/asn1crypto/csr.py#L94) is using [SignedDigestInfo](https://github.com/wbond/asn1crypto/blob/master/asn1crypto/algos.py#L190-L210).

I'll update asn1crypto to enforce a `Null` value when one of the appropriate OIDs is specified. This way each application using it doesn't need to know about the wrinkle.

**Comment by wbond** [comment]
This should be resolved by https://github.com/wbond/asn1crypto/commit/bfbb410615608880a32de49d3c99b5c26324fe92. I'll hold off on closing this until the next release of asn1crypto is done.

It sound like you've got something to report there, so I'll wait to do that release until we've addressed the issue you've identified.

**Comment by williampiras** [comment]
That's awesome! 
Thanks

**Comment by wbond** [comment]
asn1crypto 0.18.1 has been out for a while, and I just pushed out csrbuilder 0.10.1, which updates the dependency upon it to that version.
